using System;
using System.Data;
using System.Data.SqlClient;

namespace Student_Assessment_System_with_Item_Analysis.Source.Repositories
{
    public class DashboardRepository
    {
        // ADJUST THIS CONNECTION STRING IF NEEDED
        private string connectionString = @"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=StudentAssessmentDB;Integrated Security=True;";

        public DataTable GetRecentReports()
        {
            DataTable dt = new DataTable();

            using (SqlConnection con = new SqlConnection(connectionString))
            {
                // This Query Joins Reports with Users and Subjects to get names instead of IDs
                string query = @"
                    SELECT TOP 10 
                        r.Title AS [Report Title], 
                        s.SubjectCode AS [Subject], 
                        r.CreatedDate AS [Date], 
                        u.Username AS [Generated By]
                    FROM Reports r
                    INNER JOIN Subjects s ON r.SubjectID = s.SubjectID
                    INNER JOIN Users u ON r.CreatedByUserID = u.UserID
                    ORDER BY r.CreatedDate DESC";

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    try
                    {
                        con.Open();
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        da.Fill(dt);
                    }
                    catch (Exception ex)
                    {
                        // Return empty table if error, prevents crash
                        Console.WriteLine("Error fetching recent reports: " + ex.Message);
                    }
                }
            }
            return dt;
        }

        // Helper for the Counts (Active Users, etc)
        public int GetCount(string tableName)
        {
            int count = 0;
            using (SqlConnection con = new SqlConnection(connectionString))
            {
                string query = $"SELECT COUNT(*) FROM {tableName}";
                if (tableName == "Users") query += " WHERE IsActive = 1"; // Example filter

                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    try
                    {
                        con.Open();
                        count = (int)cmd.ExecuteScalar();
                    }
                    catch { count = 0; }
                }
            }
            return count;
        }
    }
}